//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerificaFirme.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Modulo()
        {
            this.ModuloNominativo = new HashSet<ModuloNominativo>();
        }
    
        public int ID { get; set; }
        public int IDProcedimento { get; set; }
        public string CodicePostazione { get; set; }
        public int Numero { get; set; }
        public bool IsNullo { get; set; }
        public int NumeroRighe { get; set; }
        public string CodComuneListaElettorale { get; set; }
        public string CodCategoriaEsclusione { get; set; }
        public bool IsCompleto { get; set; }
        public string UsernameCreazione { get; set; }
        public System.DateTime DataOraCreazione { get; set; }
        public string UsernameModifica { get; set; }
        public Nullable<System.DateTime> DataOraModifica { get; set; }
    
        public virtual CategorieEsclusione CategorieEsclusione { get; set; }
        public virtual ProcedimentoPostazione ProcedimentoPostazione { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuloNominativo> ModuloNominativo { get; set; }
    }
}
