//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerificaFirme.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuloNominativo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModuloNominativo()
        {
            this.ModuloNominativoLog = new HashSet<ModuloNominativoLog>();
        }
    
        public int IDModulo { get; set; }
        public int NumeroRiga { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public Nullable<System.DateTime> DataNascita { get; set; }
        public string CodComuneNascita { get; set; }
        public string CodComuneListaElettorale { get; set; }
        public string NListaElettorale { get; set; }
        public string CodCategorieEsclusione { get; set; }
        public string CodCategorieSanabilita { get; set; }
        public string Note { get; set; }
    
        public virtual CategorieEsclusione CategorieEsclusione { get; set; }
        public virtual CategorieSanabilita CategorieSanabilita { get; set; }
        public virtual Modulo Modulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuloNominativoLog> ModuloNominativoLog { get; set; }
    }
}
