//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerificaFirme.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procedimento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Procedimento()
        {
            this.ProcedimentoPostazione = new HashSet<ProcedimentoPostazione>();
            this.Utente = new HashSet<Utente>();
        }
    
        public int ID { get; set; }
        public string CodStato { get; set; }
        public string Descrizione { get; set; }
        public int QuorumFirme { get; set; }
        public int NumeroPostazioni { get; set; }
        public int NumeroModuli { get; set; }
        public int AnnoFirmatario { get; set; }
        public string UsernameCreazione { get; set; }
        public System.DateTime DataOraCreazione { get; set; }
        public string UsernameModifica { get; set; }
        public System.DateTime DataOraModifica { get; set; }
    
        public virtual Stato Stato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcedimentoPostazione> ProcedimentoPostazione { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Utente> Utente { get; set; }
    }
}
