//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerificaFirme.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcedimentoPostazione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProcedimentoPostazione()
        {
            this.Modulo = new HashSet<Modulo>();
        }
    
        public int IDProcedimento { get; set; }
        public string CodicePostazione { get; set; }
        public int ModuloDa { get; set; }
        public int ModuloA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Modulo> Modulo { get; set; }
        public virtual Procedimento Procedimento { get; set; }
    }
}
