//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerificaFirme.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtenteProfilo
    {
        public string Username { get; set; }
        public int IDProfilo { get; set; }
        public System.DateTime ValidoDal { get; set; }
        public Nullable<System.DateTime> ValidoAl { get; set; }
    
        public virtual Profilo Profilo { get; set; }
        public virtual Utente Utente { get; set; }
    }
}
